---
- name: Tuesday Challenge
  hosts: planetexpress          # TYPO- planetexpress, not planet express
  gather_facts: yes             # you can use yes, Yes, True, or true (but not affirmative)

  tasks:                        # WRONG TASK ORDER- make dir first, then file
   - name: create a directory
     file: 
       dest: challenge
       state: directory         # TYPO- directory, not directry
 
   - name: creating a file       # SYNTAX- needs a whitespace after the "-"
     copy:                                 # INDENTATION
       dest: challenge/challengefile.txt   # ERRORS ON THESE
       content: "Success!"                 # THREE LINES... also it is "content" NOT "contents"
